return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "bash-language-server",
      "css-lsp",
      "delve",
      "emmet-language-server",
      "emmet-ls",
      "eslint-lsp",
      "gofumpt",
      "goimports",
      "golangci-lint",
      "gomodifytags",
      "gopls",
      "hadolint",
      "html-lsp",
      "impl",
      "lua-language-server",
      "luau-lsp",
      "marksman",
      "prettier",
      "prettierd",
      "prisma-language-server",
      "protolint",
      "shellcheck",
      "shfmt",
      "some-sass-language-server",
      "stylua",
      "tailwindcss-language-server",
      "typescript-language-server",
      "vtsls",
    },
  },
}
