return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "git_config",
      "go",
      "gomod",
      "gosum",
      "gowork",
      "html",
      "javascript",
      "jsdoc",
      "json",
      "json5",
      "jsonc",
      "lua",
      "luadoc",
      "luap",
      "luau",
      "markdown",
      "markdown_inline",
      "printf",
      "prisma",
      "proto",
      "python",
      "query",
      "regex",
      "scss",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
    },
  },
}
